### PR TITLE
Add new owners

### PR DESCRIPTION
**Pull request by KlwntSingh**
### Changelog
Added Pramita, Tatenda and Kulwant as owners

#### What this PR does / why we need it:
Add new owners

#### Which issue(s) this PR fixes:

### CODE REVIEW

**Comment by tzifudzi** [comment]
@KlwntSingh I suggest you close this PR and open a new PR with request for you as an owner by yourself so you don't have to wait on me and Pramita being members.

**Comment by tzifudzi** [comment]
@jayunit100 We are now all members and ready to become owners. Should help with collaborating quicker without relying on you and Amim too much for merging changes. If all looks good please respond with `\lgtm`.

**Comment by jayunit100** [comment]
why is golang-lint failing?

**Pull request merged**
