### PR TITLE
refactor tests.yaml

### PR DESCRIPTION
**Pull request by iXinqi**
remove linux_image and windows_image from tests.yaml
rename tests.yaml to testcases.yaml

### CODE REVIEW

**Comment by marosset** [comment]
@iXinqi - We had a bad VHD get published for Windows CI (used in the failing job here). We revoked that VHD and hopefully cluster provisioning will start passing again in 1-2 hours.

**Comment by iXinqi** [comment]
looks like we can't just use the env variable "KUBERNETES_VERSION" to generate the download link of pre-compiled e2e.test binary. For example, in [this pipeline](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_windows-operational-readiness/46/operational-tests-capz-windows-2019/1582792790268448768), KUBERNETES_VERSION=v1.26.0-alpha.2.242+68e110b53c8469, but the generated link ("https://dl.k8s.io/v1.26.0-alpha.2.242+68e110b53c8469/kubernetes-test-linux-amd64.tar.gz") to download e2e.test doesn't exist. cc @knabben

**Pull request merged**
